# Generated by Django 5.1.4 on 2024-12-18 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Event", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={},
        ),
        migrations.AlterModelManagers(
            name="member",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="member",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="member",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="member",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="member",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="member",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="member",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="member",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="member",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="member",
            name="password",
        ),
        migrations.RemoveField(
            model_name="member",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="username",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
